# Generated by Django 5.2 on 2025-05-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacaoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], max_length=20)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
